name: Node.js CI

on:
  push:
    branches:
      - 'development'  # Trigger on pushes to the development branch
  pull_request:
    branches:
      - 'development'  # Trigger on PRs to the development branch

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Add private key.pem as environment variable
    - name: Set up GitHub Private Key
      run: echo "${{ secrets.GITHUB_PRIVATE_KEY }}" > private_key.pem

    # Set up the .env file
    - name: Set up .env file
      run: echo "${{ secrets.ENV_FILE }}" > .env

    - run: npm ci  # Install dependencies
    - run: npm test  # Run tests
